import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Playfair_Display } from "next/font/google";

// Load Playfair Display
const playfair = Playfair_Display({
  weight: ["400", "700"], // Regular & Bold
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${playfair.className}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
